---
version: "3.8"
services:
  bus:
    image: jayaprakashsairam05/bus:latest
    ports:
      - 91:80
    deploy:
      replicas: 3
  bike:
    image: jayaprakashsairam05/bike:latest
    ports:
      - 92:80
    deploy:
      replicas: 3
  hotel:
    image: jayaprakashsairam05/hotel:latest
    ports:
      - 93:80
    deploy:
      replicas: 3
  room:
    image: jayaprakashsairam05/room:latest
    ports:
      - 94:80
    deploy:
      replicas: 3
